id: I66DB5DC3
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:24:25.131271+00:00
last_modified: 2022-12-14 18:24:25.131275+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-058-003
  eft-text-version: 1.1.5 2020
  title: Toh_154-The_Questions_of_the_Naga_King_Sagara_(2)-v2
bases:
  E931:
    source_metadata: null
    order: 1
    base_file: E931.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
